### ISSUE TITLE
Sum of words for each year has problem

### ISSUE THREAD

**Issue by xylan-x** [Xinghom/peoplesAttentionInDemocracy#1]

**Comment by xylan-x** [comment]
we sum 8 words of each year, then divide all books number of that year to represent %.

Here is a critical problem:
The sum may be bigger than the number of all books that year, because different words may appear in the same book.

How about sum/5 to get average books number each year?
@Miss-ada @Victor0829

**Comment by Miss-ada** [comment]
average number makes sense!

**Comment by xylan-x** [comment]
All right, let's do this.
