### ISSUE TITLE
CSV data name

### ISSUE THREAD

**Issue by xylan-x** [Xinghom/peoplesAttentionInDemocracy#4]
plz check each word in csv files.
The word in non-English cannot display correctly.
Maybe we should use Eng or consider character encoding

**Comment by Victor0829** [comment]
So we may replace it with liberty_Hebrew, for example?

**Comment by xylan-x** [comment]
I think suffix is a little bit redundant, due to separated csv files we have. How about just use the word itself in Engilish?

**Comment by Victor0829** [comment]
@Xinghom OK, no problem

**Comment by xylan-x** [comment]
Oh~ another problem about data.
We should be careful with spelling, like year and Year
These could be a potential trouble in selecting data. @Victor0829 @Miss-ada
